packages:
  - '.'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  core-js: false
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: false
